### ISSUE TITLE
[Product DB] enable the data input by users

### ISSUE THREAD

**Issue by TaiSakuma** [simonsobs/acondbw#12]
#### enable the data input to Product DB by users

- The first release is read-only https://github.com/simonsobs/acondbw/issues/1
- Soon after the first release,  we plan to release features to let users enter new entries to Product DB
- The features are partially implemented for a few tables but disabled.
- We need to start taking the database backup.
    - **Note:** At the [first deployment](https://github.com/simonsobs/acondbw/issues/1), we didn't need to take a backup because users were not able to modify the DB. The DB contents were initially loaded and wouldn't change.
- The configuration for the deployment is described at https://github.com/simonsobs/acondbw-config-simons1/issues/2

##### To-do

- [x] implement GraphQL create mutations for all relevant tables https://github.com/simonsobs/acondbs/issues/10
- [x] implement the database migration https://github.com/simonsobs/acondbs/issues/11
- [x] implement data input form https://github.com/simonsobs/acondbw/issues/13
- [x] Implement features to back up the database https://github.com/simonsobs/acondbs/issues/12
- [x] deploy the feature https://github.com/simonsobs/acondbw-config-simons1/issues/2

**Comment by TaiSakuma** [comment]
- The feature was implemented and deployed (a few months ago)
    - Note: it is disabled now.
